title: mygumi tech-blog
description: Github pages + Jekyll
timezone: Asia/Seoul

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://hotehrud.github.io" # change this to the base hostname & protocol for your site

plugins:
  - jekyll-paginate

permalink: /:year/:month/:day/:title/

paginate: 5
paginate_path: '/page/:num/'

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: "Lee junghyun"
image: /thumbnail-jumbo.png
twitter:
  username: hotehrud
#  site:
facebook:
  #publisher: 1592372034171500
  #profile_id: 1809805629
  app_id: 1798910940422432 # cayman-blog
  #authors: lorepirri
#  admins:
